name: ci-golang-workflow

# Aqui estamos especificando que sempre que fizermos um push o workflow vai rodar.
on:  #bom aqui eu estou configurando para sempre que eu rodar este arquivo ele vai fazer um pull_request na branch develop
   pull_request:
     branches:
       - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2 # Aqui pegamos os dados do que acabamos de subir e ele baixa na nossa máquina, ou seja, é um git checkout

      - name: Setup do ambiente Go
        uses: actions/setup-go@v2 # Aqui nós baixamos o ambiente Golang
        with:
          go-version: 1.22.1

      - name: Executar testes
        run: go test

      - name: Executar aplicação
        run: go run math.go